name: Backend CD

on:
  push:
    branches:
      - main
    paths:
      - 'starter/backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set image tag
        id: vars
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPO_BACKEND }}:$IMAGE_TAG .

      - name: Push to ECR
        run: docker push ${{ secrets.ECR_REPO_BACKEND }}:$IMAGE_TAG

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name cluster

      - name: Set image in kustomize
        run: |
          cd k8s
          kustomize edit set image backend=${{ secrets.ECR_REPO_BACKEND }}:$IMAGE_TAG

      - name: Apply Kubernetes manifests
        run: |
          cd k8s
          kustomize build | kubectl apply -f -

